export const ALERTS = {
  WRONG: "Wrong user or password.",
  PASSWORD_NOT_MATCH: "Password does not match.",
  SIGNIN_SUCCESS: 'User created successfully.',
  FAILURE: 'Something went wrong, try again.'
}

export const BUTTONS = {
  LOGIN: 'LOGIN',
  SIGNIN: 'Sign In',
  FORGOT: 'Forgot your password?',
  LANGUAGE: 'Language',
  CREATE_EXPERIENCE: 'Create Experience',
  STATISTICS: 'Statistics',
  CALENDAR: 'Calendar',
  LOGOUT: 'Log Out',
  ABOUT: 'About',
  WATER_LEVEL: 'Water Level',
  PERCENTAGE25: '25%',
  PERCENTAGE50: '50%',
  PERCENTAGE75: '75%',
  PERCENTAGE100: '100%',
  SOAP: 'Soap',
  WATER_TEMPERATURE: 'Water Temperature',
  COLD: 'Cold',
  WARM: 'Warm',
  HOT: 'Hot',
  TURN_ON: 'Turn on the shower?',
  DONE: 'Done',
  AUTOMATIC: 'Automatic',
  CONFIRM: 'Confirm',
  CANCEL: 'Cancel',
  OK: 'OK',
  CHECK_WEATHER: 'Check Weather',
  BOOK: 'Book',
}

export const NUMBER_OF_COLUMNS = 2;

export const OPTIONS = {
  SMART_SHOWER: "Smart Shower",
  SETTINGS: "Settings",
  INFORMATION: "Information",
  ROOMS: "Rooms",
  SERVICES: "Services",
  AIRPORTS: "Airports",
  CASINOS: "Casinos",
  BEACHES: "Beaches",
  GROUPS: "Groups",
  POOLS: "Pools",
  RESTAURANTS: "Restaurants",
  ZONE: "Zone Info",
  NETWORKS: "Social Networks",
  BOOK: "Book",
  EXPERIENCES: "Experiences",
  CONTACT: "Contact",
  ACTIVITIES: "Activities"
}

export const OPTIONS_SCREENS = {
  HOME: 'Home',
  SHOWER: "Shower",
  SETTINGS: "Settings",
  INFORMATION: "Information",
  ROOMS: "Rooms",
  SERVICES: "Services",
  AIRPORTS: "Airports",
  CASINOS: "Casinos",
  BEACHES: "Beaches",
  GROUPS: "Groups",
  POOLS: "Pools",
  RESTAURANTS: "Restaurants",
  ZONE: "Zone",
  NETWORKS: "Networks",
  BOOK: "Book",
  EXPERIENCES: "Experiences",
  CONTACT: "Contact",
  ACTIVITIES: "Activities",
  CREATE_EXPERIENCE: "CreateExperience"
}

export const PLACEHOLDERS = {
  NAME: 'Name',
  LASTNAME: 'Lastname',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  CHECK_PASSWORD: 'Check password',
  INITIAL_DATE: 'Initial date',
  FINAL_DATE: 'Final date',
  DATE: 'Date'
}

export const SCREENS = {
  LOGIN: "Login",
  SIGNIN: "SignIn",
  HOME: "Home",
  INFORMATION: "Information",
  ROOMS: "Rooms",
  SERVICES: "Services",
  AIRPORTS: "Airports",
  CASINOS: "Casinos",
  BEACHES: "Beaches",
  GROUPS: "Groups",
  POOLS: "Pools",
  RESTAURANTS: "Restaurants",
  ZONE: "Zone",
  NETWORKS: "Social Networks",
  BOOK: "Book",
  EXPERIENCES: "Experiences",
  CONTACT: "Contact",
  ACTIVITIES: "Activities",
  CREATE_EXPERIENCE: 'Create Experience',
  SHOWER: "Smart Shower",
  SETTINGS: "Settings",
  STATISTICS: "Statistics",
  ABOUT: "About",
}

export const VALUES = {
  URL: 'http://192.168.100.5:1337/',
  DATE_API_URL: 'http://worldclockapi.com/api/json/est/now',
  WEBPAGE: 'Web Page',
  DATE: 'Date: ',
  DATE_MODE: 'date',
  DESCRIPTION: 'Description: ',
  PLACE: 'Place: ',
  DATE_FORMAT: 'MM-DD-YYYY',
  MIN_DATE:'01-01-2016',
  MAX_DATE:'01-01-2030',
  INFORMATION: 'information',
  ROOMS: 'rooms',
  SERVICES: 'services',
  TYPES: 'types',
  AIRPORTS: "airports",
  CASINOS: "casinos",
  BEACHES: "beaches",
  GROUPS: "groups",
  POOLS: "pools",
  RESTAURANTS: "restaurants",
  CALENDARS: "calendars",
  CLIENTS: 'clients',
  AIRPORT: "Airport",
  CASINO: "Casino",
  BEACH: "Beach",
  GROUP: "Group",
  POOL: "Pool",
  ZONE: "zones",
  NETWORKS: "networks",
  EXPERIENCES: "experiences",
  CONTACT: "contacts",
  ACTIVITIES: "activities",
  RESTAURANT: "Restaurant",
  EMAIL: 'email',
  ERROR: 'Error',
  RATING: 'Rating: ',
  SELECT_DATE: 'Select the date to consult',
  WEATHER: 'Weather'
}
